package exporter

// Read-only association contracts extracted from isomorphic_server d4e9d488
// and generated_runtime bef51d8a1. This registry does not imply installed-OS
// support; each family must pass capability and response validation.
// Kept separate from the legacy pair-only exporter until traversal is wired.
var junctionFamilies = []associationFamily{
	{"anchor_to_anchor_point_associations", "ANCHORS", "ANCHOR_POINTS", "anchor", "anchor_point", "anchor", "anchorPoint"},
	{"anchor_to_asset_associations", "ANCHORS", "ASSETS", "anchor", "asset", "anchor", "asset"},
	{"anchor_to_workstream_pattern_engine_source_associations", "ANCHORS", "WORKSTREAM_PATTERN_ENGINE_SOURCES", "anchor", "source", "anchor", "workstreamPatternEngineSource"},
	{"annotation_to_anchor_associations", "ANNOTATIONS", "ANCHORS", "annotation", "anchor", "annotation", "anchor"},
	{"annotation_to_asset_associations", "ANNOTATIONS", "ASSETS", "annotation", "asset", "annotation", "asset"},
	{"connector_to_annotation_associations", "CONNECTORS", "ANNOTATIONS", "connector", "annotation", "connector", "annotation"},
	{"connector_to_conversation_associations", "CONNECTORS", "CONVERSATIONS", "connector", "conversation", "connector", "conversation"},
	{"connector_to_conversation_message_associations", "CONNECTORS", "CONVERSATION_MESSAGES", "connector", "message", "connector", "conversationMessage"},
	{"connector_to_person_associations", "CONNECTORS", "PERSONS", "connector", "person", "connector", "person"},
	{"connector_to_website_associations", "CONNECTORS", "WEBSITES", "connector", "website", "connector", "website"},
	{"connector_to_workstream_event_associations", "CONNECTORS", "WORKSTREAM_EVENTS", "connector", "workstream_event", "connector", "workstreamEvent"},
	{"connector_to_workstream_summary_associations", "CONNECTORS", "WORKSTREAM_SUMMARIES", "connector", "workstream_summary", "connector", "workstreamSummary"},
	{"conversation_message_to_anchor_associations", "CONVERSATION_MESSAGES", "ANCHORS", "message", "anchor", "conversationMessage", "anchor"},
	{"conversation_message_to_annotation_associations", "CONVERSATION_MESSAGES", "ANNOTATIONS", "message", "annotation", "conversationMessage", "annotation"},
	{"conversation_message_to_asset_associations", "CONVERSATION_MESSAGES", "ASSETS", "message", "asset", "conversationMessage", "asset"},
	{"conversation_message_to_conversation_message_associations", "CONVERSATION_MESSAGES", "CONVERSATION_MESSAGES", "message", "additional_message", "x", "y"},
	{"conversation_message_to_hint_associations", "CONVERSATION_MESSAGES", "HINTS", "message", "hint", "conversationMessage", "hint"},
	{"conversation_message_to_range_associations", "CONVERSATION_MESSAGES", "RANGES", "message", "range", "conversationMessage", "range"},
	{"conversation_message_to_website_associations", "CONVERSATION_MESSAGES", "WEBSITES", "message", "website", "conversationMessage", "website"},
	{"conversation_message_to_workstream_pattern_engine_source_associations", "CONVERSATION_MESSAGES", "WORKSTREAM_PATTERN_ENGINE_SOURCES", "message", "source", "conversationMessage", "source_"},
	{"conversation_to_anchor_associations", "CONVERSATIONS", "ANCHORS", "conversation", "anchor", "conversation", "anchor"},
	{"conversation_to_annotation_associations", "CONVERSATIONS", "ANNOTATIONS", "conversation", "annotation", "conversation", "annotation"},
	{"conversation_to_asset_associations", "CONVERSATIONS", "ASSETS", "conversation", "asset", "conversation", "asset"},
	{"conversation_to_conversation_message_associations", "CONVERSATIONS", "CONVERSATION_MESSAGES", "conversation", "message", "conversation", "conversationMessage"},
	{"conversation_to_range_associations", "CONVERSATIONS", "RANGES", "conversation", "range", "conversation", "range"},
	{"conversation_to_tag_associations", "CONVERSATIONS", "TAGS", "conversation", "tag", "conversation", "tag"},
	{"conversation_to_website_associations", "CONVERSATIONS", "WEBSITES", "conversation", "website", "conversation", "website"},
	{"conversation_to_workstream_pattern_engine_source_associations", "CONVERSATIONS", "WORKSTREAM_PATTERN_ENGINE_SOURCES", "conversation", "source", "conversation", "workstreamPatternEngineSource"},
	{"entity_to_subscription_associations", "ENTITIES", "SUBSCRIPTIONS", "entity", "subscription", "entity", "subscription"},
	{"entity_to_user_associations", "ENTITIES", "USERS", "entity", "user", "entity", "user"},
	{"fingerprint_to_person_associations", "FINGERPRINTS", "PERSONS", "fingerprint", "person", "fingerprint", "person"},
	{"fingerprint_to_workstream_event_associations", "FINGERPRINTS", "WORKSTREAM_EVENTS", "fingerprint", "workstream_event", "fingerprint", "workstream_event"},
	{"hint_to_asset_associations", "HINTS", "ASSETS", "hint", "asset", "hint", "asset"},
	{"person_to_anchor_associations", "PERSONS", "ANCHORS", "person", "anchor", "person", "anchor"},
	{"person_to_annotation_associations", "PERSONS", "ANNOTATIONS", "person", "annotation", "person", "annotation"},
	{"person_to_asset_associations", "PERSONS", "ASSETS", "person", "asset", "person", "asset"},
	{"person_to_conversation_message_associations", "PERSONS", "CONVERSATION_MESSAGES", "person", "message", "person", "conversationMessage"},
	{"person_to_person_associations", "PERSONS", "PERSONS", "person", "additional_person", "x", "y"},
	{"person_to_tag_associations", "PERSONS", "TAGS", "person", "tag", "person", "tag"},
	{"person_to_website_associations", "PERSONS", "WEBSITES", "person", "website", "person", "website"},
	{"person_to_workstream_pattern_engine_source_associations", "PERSONS", "WORKSTREAM_PATTERN_ENGINE_SOURCES", "person", "source", "person", "source_"},
	{"pipeline_to_connector_associations", "PIPELINES", "CONNECTORS", "pipeline", "connector", "pipeline", "connector"},
	{"pipeline_to_range_associations", "PIPELINES", "RANGES", "pipeline", "range", "pipeline", "range"},
	{"pipeline_to_schedule_associations", "PIPELINES", "SCHEDULES", "pipeline", "schedule", "pipeline", "schedule"},
	{"pipeline_to_signal_associations", "PIPELINES", "SIGNALS", "pipeline", "signal", "pipeline", "signal"},
	{"pipeline_to_website_associations", "PIPELINES", "WEBSITES", "pipeline", "website", "pipeline", "website"},
	{"pipeline_to_workstream_pattern_engine_source_associations", "PIPELINES", "WORKSTREAM_PATTERN_ENGINE_SOURCES", "pipeline", "source", "pipeline", "source"},
	{"pipeline_to_workstream_summary_associations", "PIPELINES", "WORKSTREAM_SUMMARIES", "pipeline", "workstream_summary", "pipeline", "workstreamSummary"},
	{"signal_to_annotation_associations", "SIGNALS", "ANNOTATIONS", "signal", "annotation", "signal", "annotation"},
	{"signal_to_person_associations", "SIGNALS", "PERSONS", "signal", "person", "signal", "person"},
	{"signal_to_range_associations", "SIGNALS", "RANGES", "signal", "range", "signal", "range"},
	{"signal_to_website_associations", "SIGNALS", "WEBSITES", "signal", "website", "signal", "website"},
	{"signal_to_workstream_event_associations", "SIGNALS", "WORKSTREAM_EVENTS", "signal", "workstream_event", "signal", "workstream_event"},
	{"signal_to_workstream_summary_associations", "SIGNALS", "WORKSTREAM_SUMMARIES", "signal", "workstream_summary", "signal", "workstream_summary"},
	{"subscription_to_user_associations", "SUBSCRIPTIONS", "USERS", "subscription", "user", "subscription", "user"},
	{"tag_to_anchor_associations", "TAGS", "ANCHORS", "tag", "anchor", "tag", "anchor"},
	{"tag_to_annotation_associations", "TAGS", "ANNOTATIONS", "tag", "annotation", "tag", "annotation"},
	{"tag_to_asset_associations", "TAGS", "ASSETS", "tag", "asset", "tag", "asset"},
	{"tag_to_conversation_message_associations", "TAGS", "CONVERSATION_MESSAGES", "tag", "message", "tag", "conversationMessage"},
	{"tag_to_website_associations", "TAGS", "WEBSITES", "tag", "website", "tag", "website"},
	{"tag_to_workstream_event_associations", "TAGS", "WORKSTREAM_EVENTS", "tag", "workstream_event", "tag", "workstreamEvent"},
	{"tag_to_workstream_pattern_engine_source_window_associations", "TAGS", "WORKSTREAM_PATTERN_ENGINE_SOURCE_WINDOWS", "tag", "source_window", "tag", "sourceWindow"},
	{"tag_to_workstream_summary_associations", "TAGS", "WORKSTREAM_SUMMARIES", "tag", "workstream_summary", "tag", "workstreamSummary"},
	{"website_to_annotation_associations", "WEBSITES", "ANNOTATIONS", "website", "annotation", "website", "annotation"},
	{"website_to_asset_associations", "WEBSITES", "ASSETS", "website", "asset", "website", "asset"},
	{"website_to_workstream_pattern_engine_source_associations", "WEBSITES", "WORKSTREAM_PATTERN_ENGINE_SOURCES", "website", "source", "website", "source_"},
	{"website_to_workstream_pattern_engine_source_window_associations", "WEBSITES", "WORKSTREAM_PATTERN_ENGINE_SOURCE_WINDOWS", "website", "source_window", "website", "sourceWindow"},
	{"workstream_event_to_anchor_associations", "WORKSTREAM_EVENTS", "ANCHORS", "workstream_event", "anchor", "workstreamEvent", "anchor"},
	{"workstream_event_to_annotation_associations", "WORKSTREAM_EVENTS", "ANNOTATIONS", "workstream_event", "annotation", "workstreamEvent", "annotation"},
	{"workstream_event_to_conversation_message_associations", "WORKSTREAM_EVENTS", "CONVERSATION_MESSAGES", "workstream_event", "message", "workstreamEvent", "conversationMessage"},
	{"workstream_event_to_hint_associations", "WORKSTREAM_EVENTS", "HINTS", "workstream_event", "hint", "workstreamEvent", "hint"},
	{"workstream_event_to_person_associations", "WORKSTREAM_EVENTS", "PERSONS", "workstream_event", "person", "workstream_event", "person"},
	{"workstream_event_to_website_associations", "WORKSTREAM_EVENTS", "WEBSITES", "workstream_event", "website", "workstreamEvent", "website"},
	{"workstream_event_to_workstream_pattern_engine_source_associations", "WORKSTREAM_EVENTS", "WORKSTREAM_PATTERN_ENGINE_SOURCES", "workstream_event", "source", "workstreamEvent", "source_"},
	{"workstream_event_to_workstream_pattern_engine_source_window_associations", "WORKSTREAM_EVENTS", "WORKSTREAM_PATTERN_ENGINE_SOURCE_WINDOWS", "workstream_event", "source_window", "workstreamEvent", "sourceWindow"},
	{"workstream_summary_to_anchor_associations", "WORKSTREAM_SUMMARIES", "ANCHORS", "workstream_summary", "anchor", "workstreamSummary", "anchor"},
	{"workstream_summary_to_annotation_associations", "WORKSTREAM_SUMMARIES", "ANNOTATIONS", "workstream_summary", "annotation", "workstreamSummary", "annotation"},
	{"workstream_summary_to_asset_associations", "WORKSTREAM_SUMMARIES", "ASSETS", "workstream_summary", "asset", "workstreamSummary", "asset"},
	{"workstream_summary_to_conversation_associations", "WORKSTREAM_SUMMARIES", "CONVERSATIONS", "workstream_summary", "conversation", "workstreamSummary", "conversation"},
	{"workstream_summary_to_conversation_message_associations", "WORKSTREAM_SUMMARIES", "CONVERSATION_MESSAGES", "workstream_summary", "message", "workstreamSummary", "conversationMessage"},
	{"workstream_summary_to_hint_associations", "WORKSTREAM_SUMMARIES", "HINTS", "workstream_summary", "hint", "workstreamSummary", "hint"},
	{"workstream_summary_to_person_associations", "WORKSTREAM_SUMMARIES", "PERSONS", "workstream_summary", "person", "workstreamSummary", "person"},
	{"workstream_summary_to_range_associations", "WORKSTREAM_SUMMARIES", "RANGES", "workstream_summary", "range", "workstreamSummary", "range"},
	{"workstream_summary_to_website_associations", "WORKSTREAM_SUMMARIES", "WEBSITES", "workstream_summary", "website", "workstreamSummary", "website"},
	{"workstream_summary_to_workstream_event_associations", "WORKSTREAM_SUMMARIES", "WORKSTREAM_EVENTS", "workstream_summary", "workstream_event", "workstreamSummary", "workstreamEvent"},
	{"workstream_summary_to_workstream_pattern_engine_source_associations", "WORKSTREAM_SUMMARIES", "WORKSTREAM_PATTERN_ENGINE_SOURCES", "workstream_summary", "source", "workstreamSummary", "source_"},
	{"workstream_summary_to_workstream_summaries_associations", "WORKSTREAM_SUMMARIES", "WORKSTREAM_SUMMARIES", "workstream_summary", "additional_workstream_summary", "x", "y"},
}

func junctionFamilyByName(name string) (associationFamily, bool) {
	for _, f := range junctionFamilies {
		if f.name == name {
			return f, true
		}
	}
	return associationFamily{}, false
}
